apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: TableTennisShop
build:
  local:
    push: false
  artifacts:
  # Auth
    - image: nguyennoah/auth-ttshop
      context: auth
      docker:
        dockerfile: Dockerfile
  # Product
    - image: nguyennoah/product-ttshop
      context: product
      docker:
        dockerfile: Dockerfile
  #Payment
    - image: nguyennoah/payment-ttshop
      context: payment
      docker:
        dockerfile: Dockerfile
  #Order
    - image: nguyennoah/order-ttshop
      context: order
      docker:
        dockerfile: Dockerfile
  #Inventory
    - image: nguyennoah/inventory-ttshop
      context: inventory
      docker:
        dockerfile: Dockerfile
  #Expiration
    - image: nguyennoah/expiration-ttshop
      context: expiration
      docker:
        dockerfile: Dockerfile
  #Client
    - image: nguyennoah/client-ttshop
      context: client
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/nats-depl.yaml
    - infra/k8s/nats-clusterIP.yaml
    - infra/k8s/*.yaml
deploy:
  kubectl:
    hooks:
      before:
        - host:
            command: ["docker", "pull", "mongo:8.0.10-rc0"]
        - host:
            command: ["docker", "pull", "redis:6.0.3-alpine"]
        - host:
            command: ["docker", "pull", "docker.io/library/nats-streaming:0.17.0"]
        - host:
            command: ["docker", "pull", "minio/minio"]
  statusCheckDeadlineSeconds: 600
