apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: TableTennisShop
build:
  artifacts:
  # Auth
    - image: nguyennoah/auth-ttshop
      context: auth
      docker:
        dockerfile: Dockerfile
  # Product
    - image: nguyennoah/product-ttshop
      context: product
      docker:
        dockerfile: Dockerfile
  #Payment
    - image: nguyennoah/payment-ttshop
      context: payment
      docker:
        dockerfile: Dockerfile
  #Order
    - image: nguyennoah/order-ttshop
      context: order
      docker:
        dockerfile: Dockerfile
  #Inventory
    - image: nguyennoah/inventory-ttshop
      context: inventory
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/*
