apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: config-mongo-service
spec:
  selector:
    app: config-mongo
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-mongo-deployment
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: config-mongo
  template:
    metadata:
      labels:
        app: config-mongo
    spec:
      containers:
        - name: config-mongo
          image: mongo:8.0.10-rc0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: config-mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: config-mongo-persistent-storage
          persistentVolumeClaim:
            claimName: config-mongo-pvc
